課題①-3のarray.htmlとarray.jsファイルを作成しました。
Takahiro-Masuda-0306/javascript-kadai-1 pull request #2
Opened 2020-09-14 16:27 UTC by Takahiro-Masuda-0306

コードレビューをお願いいたします！

2020-09-15 12:32 UTC, myzktkyk requested changes
指摘が1点、確認事項が1点それぞれございます。

2020-09-15 12:32 UTC, myzktkyk commented on js/array.js
> +    document.getElementById("task").innerHTML += i + ":" + log[i] + "<br>";
課題の gif ではコンソールに出力するようになっていたかと思いますが
HTML に出力しているのはどのような意図でしょうか？ 😕

2020-09-15 12:32 UTC, myzktkyk commented on js/array.js
> +function add_task(task) {
javascript は `camelCase` が一般的です。

2020-09-16 13:43 UTC, myzktkyk requested changes
修正内容に問題があるように見えます。お手数ですが、再度確認していただけますか？

2020-09-17 06:10 UTC, Takahiro-Masuda-0306 commented
> console.log では課題の gif と同じ出力が得られないと思います。
僕がいまいち課題に関する認識をうまくできていないのだと思いますが、質問させてください！
今回は上記のように内容を変更させていただいたのですが、そもそも`console.log`を使うことがダメということでしょうか？
もしくは前回提出分は配列のままconsoleに表示していたのがダメということでしょうか？

是非よろしくお願いいたします！

2020-09-18 10:37 UTC, kouki-iwahara commented on js/array.js
> +var log = ["掃除", "買い物", "散歩"];
var は現在ほぼ使用されませんので、letかconstの適切な方を使用しましょう。
また、配列であれば命名は複数形にしましょう。

2020-09-18 10:37 UTC, kouki-iwahara commented on js/array.js
> +const task = prompt("新しいタスクを追加");
文字列は`””`ではなく`’’`で囲む慣習がありますので、`''`で統一しましょう。

2020-09-18 13:19 UTC, myzktkyk commented
>今回は上記のように内容を変更させていただいたのですが、
>そもそもconsole.logを使うことがダメということでしょうか？
>もしくは前回提出分は配列のままconsoleに表示していたのがダメということでしょうか？

gif では以下の通り Console に出力されてたかと思います。

```
===============
現在持っているタスクの一覧
===============
0 : 掃除
1 : 買い物
2 : 散歩
```

今のコード `console.log(log)` ではこのような出力にはなりませんよね？という指摘でした 🙏

2020-09-18 18:35 UTC, Takahiro-Masuda-0306 commented
承知しました！

今回の修正分ではまだ不十分でしょうか？
「===============」という文字列をコンソールに表示することも。今回の課題内容に含まれているのでしょうか？

2020-09-19 12:47 UTC, myzktkyk requested changes
頂いていたコメントの回答も含めてレビューさせていただきました 🙏

2020-09-19 12:47 UTC, myzktkyk commented on js/array.js
> +var log = ["掃除", "買い物", "散歩"];
こちら、指摘内容が反映されていないようです。
さらにもう1点付け加えさせていただくと…
 `log` という名前だと実態を表していないかなと思います。

2020-09-19 12:47 UTC, myzktkyk commented on js/array.js
> +  console.log('現在持っているタスク一覧');
>「===============」という文字列をコンソールに表示することも。今回の課題内容に含まれているのでしょうか？

課題では「これが仕様です」とは明確に言っていませんが
かといって、イメージの gif と敢えて違う出力をする必然性、理由もまたないと思っています。

2020-09-19 12:47 UTC, myzktkyk commented on js/array.js
> +  log.forEach(function(task, index) {
せっかくならアロー関数で記述した方がモダンでいいと思います。
```suggestion
  log.forEach((task, index) => {
```

2020-09-19 19:18 UTC, Takahiro-Masuda-0306 commented
何度も申し訳ございません。
課題①-3のarray.jsファイルを修正させていただきました。

**●修正内容**
変数の定義方法の修正（var → let）
文字列の追加（「===============」のコンソール表示）
関数の定義方法の修正（アロー関数への修正）

2020-09-19 19:37 UTC, Takahiro-Masuda-0306 commented
何度も申し訳ございません。
課題①-3のarray.jsファイルを修正させていただきました。

**●修正内容**
①変数の定義方法の修正（var → let）
②文字列の追加（「===============」のコンソール表示）
③関数の定義方法の修正（アロー関数への修正）
④変数名の変更（log → todos）
⑤文字列の囲いの変更（" → '）

2020-09-19 19:54 UTC, Takahiro-Masuda-0306 commented
また一度間違えてpushをしてしまったのですが、これに対しての対策としては
①git reset --hard HEAD^
②git push -f origin develop
として強制pushするか、
①git revert 
②git push origin develop
として追加のpushをするのはどちらが得策でしょうか？

今回は強制pushをさせていただいたのですが、これはやめた方がいいのでしょうか？
（また今回の強制pushを誤ってファイル変更前にしてしまいました。。。）

2020-09-20 22:29 UTC, kouki-iwahara commented on js/array.js
> +let todos = ['掃除', '買い物', '散歩'];
cosnt で定義できます。
最代入される場合はlet、されない場合はletです。
(なるべくconstで定義できる設計が望ましいです。)

2020-09-20 22:29 UTC, kouki-iwahara commented on js/array.js
> +  console.log(`
``を使用する時は${}で変数の中身を文字列で表したい時だけにしましょう。

2020-09-20 22:37 UTC, kouki-iwahara commented
> また一度間違えてpushをしてしまったのですが、これに対しての対策としては
> ①git reset --hard HEAD^
> ②git push -f origin develop
> として強制pushするか、
> ①git revert
> ②git push origin develop
> として追加pushをするのはどちらが得策でしょうか？
> 
> 今回は強制pushをさせていただいたのですが、これはやめた方がいいのでしょうか？
> （また今回の強制pushを誤ってファイル変更前にしてしまったのですが、これ以上いじるのは取り返しのつかないことになるかと思い、怖くてやめておきました。。。）

どちらでも良いですが、commit履歴が残るか否かの違いになります。
課題でただのcommit間違いとかなら履歴は不要ですが、業務であれば履歴を残した方が良いケースや業務上のルールが関係してきますので、その時の責任者に相談してどうするか聞いちゃっても良いかもです。

一応ですが、forceでpushしても「強制的にpushした」という履歴は残るので、あとで質問されても良いようにはしておいた方が良いかと。

2020-09-21 03:58 UTC, Takahiro-Masuda-0306 commented
お世話になっております。
課題①-3のarray.jsを修正いたしましたので、レビューをよろしくお願いいたします！

**●修正内容**
①変数の定義の変更（let → const）
②文字列の囲いの変更（` → '）

よろしくお願いします！

2020-09-21 10:07 UTC, merged